### ISSUE TITLE
Crash in DsaKeyPublicV2Blob's clone_from_parts

### ISSUE THREAD

**Issue by nwalfield** [emgre/win-crypto-ng#39]
A user of Sequoia's Octopus reported [this bug](https://gitlab.com/sequoia-pgp/sequoia-octopus-librnp/-/issues/40).

They provided a [backtrace](https://gitlab.com/sequoia-pgp/sequoia-octopus-librnp/uploads/a394d1861bba196025b17d78bbae0f2c/octopus-crash-64bit.txt).  The most relevant bit is:

```text
Logging to "C:\\Users\\jorgk\\AppData\\Roaming\\Thunderbird\\Profiles/8qf0aj6a.SQ test\\octopus.log"
thread '<unnamed>' panicked at 'source slice length (256) does not match destination slice length (255)', /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\slice\mod.rs:3058:13
...
  16:     0x7fff1ba0fb2d - core::slice::impl$0::copy_from_slice<u8>
                               at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b\library\core\src\slice\mod.rs:3058
  17:     0x7fff1ba290fc - win_crypto_ng::helpers::blob::Blob<enum$<win_crypto_ng::key_blob::DsaKeyPublicV2Blob> >::clone_from_parts
                               at C:\Users\jorgk\.cargo\registry\src\github.com-1285ae84e5963aae\win-crypto-ng-0.4.0\src\helpers\blob.rs:138
  18:     0x7fff1b72eb91 - enum$<sequoia_openpgp::packet::Key<sequoia_openpgp::packet::key::PublicParts,sequoia_openpgp::packet::key::PrimaryRole>, V4>::verify<sequoia_openpgp::packet::key::PublicParts,sequoia_openpgp::packet::key::PrimaryRole>
                               at C:\Users\jorgk\.cargo\registry\src\github.com-1285ae84e5963aae\sequoia-openpgp-1.3.1\src\crypto\backend\cng\asymmetric.rs:528
...
```

That is, it is panicking in the [blob macro](https://github.com/emgre/win-crypto-ng/blob/master/src/helpers/blob.rs#L96) while [copying](https://github.com/emgre/win-crypto-ng/blob/master/src/helpers/blob.rs#L138) a [`DsaKeyPublicV2Blob`'s]( https://github.com/emgre/win-crypto-ng/blob/master/src/key_blob.rs#L318) fields:

```
            pub fn clone_from_parts(header: &$header, tail: &$tail_ident) -> Box<Self> {
                let header_len = core::mem::size_of_val(header);
                let tail_len: usize = 0 $( + blob! { size: header, $($len)*} )*;

                // NOTE: There's no trailing padding due to `Blob` being `repr(packed)`
                let mut boxed = vec![0u8; header_len + tail_len].into_boxed_slice();

                let header_bytes = $crate::helpers::AsBytes::as_bytes(header);
                &mut boxed[..header_len].copy_from_slice(header_bytes);
                let mut offset = header_len;
                $(
                    let field_len = blob! { size: header, $($len)*};
                    &mut boxed[offset..offset + field_len].copy_from_slice(tail.$field); // <--- PANICS HERE
                    offset += field_len;
                )*
```

Since the lengths are computed in this function and the data structure is defined by this crate, I suspect that this might be an issue with this crate.

Here is where [we are calling `clone_from_parts`](https://gitlab.com/sequoia-pgp/sequoia/-/blob/openpgp/v1.3.1/openpgp/src/crypto/backend/cng/asymmetric.rs#L528).  It's quite possible that we are doing something wrong.  If you have any hints, I'd appreciate it.  To make this type of issue easier to debug in the future, it would be helpful to add some asserts to make clear what field is causing the issue.

**Comment by emgre** [comment]
I'm not an expert in DSA, but I have generated a 2048 bit private key using openssl, and by printing it using `openssl dsa -text`, I see that `y` and `g` are indeed 256 bytes, but `p` has one extra byte. This would explain the panic. Windows CNG forces us to have the same length for `p` (modulus), `g` (generator) and `y` (public), since they all share the same length component (`cbKey`).

tbh, I don't know what we are supposed to do here. If a DSA expert wants to chime in, that would really help.

**Comment by emgre** [comment]
Oh, it seems the extra byte is because the first byte of my modulus (`0x8F`) was creating a negative number. ASN.1 DER encoding prescribes an extra `0x00` in front of an `INTEGER` to make sure that it's interpreted as a positive number.

So, I guess in your code you should always make sure that you only send the `cbKey` least-significant bytes for the `p`, `g` and `y` components, or remove the extra byte earlier in your code path.

**Comment by emgre** [comment]
We should probably provide a `AsymmetricKey::<Dsa, Public>::import_from_parts` like we do for other algorithms and handle all of this ourselves, so you wouldn't have to build the blog by yourself (which is quite cumbersome). I think we didn't provide it because of the whole V1/V2 thing. I'll give it some thought and probably implement it this week-end. I'll also add some asserts as you suggested, to know which field created the issue.

**Comment by nwalfield** [comment]
Sorry for the late follow up.  The asserts helped us to debug the issue, which was on our side.  Thanks!
