### ISSUE TITLE
X::clone_from_parts interface is brittle to the point of being unsafe

### ISSUE THREAD

**Issue by teythoon** [emgre/win-crypto-ng#44]
I recently fixed a crash in Sequoia's CNG backend:

- https://gitlab.com/sequoia-pgp/sequoia/-/jobs/3857282438#L746
- https://gitlab.com/sequoia-pgp/sequoia/-/commit/58fa8e0282e76c63295018c0953122209063a802

It comes down to the fact that the intimate relationship between a field's length in the header and the field itself in the body is exposed via the public `X::clone_from_parts` interface.  I think this interface should be private (or at least marked as unsafe), and a safe alternative should be provided.

**Comment by cbeuw** [comment]
It's brittle, but after a brief look at it I don't think it's unsound. The crash was an assertion failure due to length mismatch in `copy_from_slice`, which is a documented behaviour and does not cause memory corruption or UB. If you supply the wrong thing to `clone_from_parts`, the worst thing that could happen is getting the wrong result, but the [deserialised fields](https://github.com/emgre/win-crypto-ng/blob/b7d9d80f1812bd9adf918af2954220091353ef6d/src/key_blob.rs) do not influence the address and size of any (unchecked) memory access (they are "pure data"), so I don't think it's necessary to mark them unsafe.

**Comment by emgre** [comment]
I was planning to mark them as unsafe, just as a safeguard and a not-too-breaking change, but haven't analyze it much. Would you recommend simply documenting the behaviour @cbeuw?

**Comment by cbeuw** [comment]
I would simply document it and spare the not-strictly-necessary unsafe.

**Comment by emgre** [comment]
Does #45 addresses your concerns, @teythoon and @cbeuw?

**Comment by teythoon** [comment]
Yes, that is better.
